name = "mame-proxy"
main = "worker.mjs"
compatibility_date = "2024-01-01"

[vars]
# Point to your GitHub Pages origin (must include trailing slash)
ORIGIN = "https://<username>.github.io/<repo>/"

# Optional: automatically bind to a route like mame.reb.ai/*
# Uncomment and set zone_id / route if you prefer routing via wrangler
#
# [routes]
# pattern = "mame.reb.ai/*"
# zone_id = "<your-zone-id>"


